#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BattleSquid.Resource", IsApplication=true)]

namespace BattleSquid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.0.99")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int bomb = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int bomb_gray = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int hit = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int squid_boom = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int squid_icon = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int X = 2130771973;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7F030000
			public const int HoorayYay = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Kerboom = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int KillYay = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int LoseYell = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int Sploosh = 2130903044;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int kerboomFile = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
